### ISSUE TITLE
PgHydro on PostGreSQL 10 / PostGIS 2.4 ?

### ISSUE THREAD

**Issue by Doctor-Who** [pghydro/pghydro#10]
Hi,

Thanks for release that tools which seems amazing.
I wonder if you have already test your extension on PostGreSQL 10 and PostGIS 2.4 ? 
As I don't mastering all the features of your script, I won't be able to clearly identify if it's due to usage or software compatibility 

Thanks !

**Comment by pghydro** [comment]
Hi Doctor,

I didnt tried it with PostGreSQL 10 and PostGIS 2.4, but as we use simple functions I dont think will´ll have any issues with that.

I suggest you to use pghydrotools that is a QGIS plugin that is an interface to use all the process and functionallity of pghydro.

1st - Install pghydro.
2nd - Install pghydrotools QGIS plugin

If you have any problems, let me know.

Alex

**Comment by Doctor-Who** [comment]
Ok I gonna update my database server and tell you if it's works.
Thanks for kind advice.
